<?xml version="1.0"?>
<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">
        <!-- Put here the robot description -->
<xacro:property name="PI" value="3.1415926535897931"/>

<xacro:property name="cameraSize" value="0.05"/>
<xacro:property name="cameraMass" value="0.1"/>

<xacro:property name="chassisHeight" value="0.2"/>
<xacro:property name="chassisRadius" value="0.2"/>
<xacro:property name="chassisMass" value="5"/>

<xacro:property name="casterRadius" value="0.05"/>
<xacro:property name="casterMass" value="3"/>

<xacro:property name="wheelWidth" value="0.03"/>
<xacro:property name="wheelRadius" value="0.1"/>
<xacro:property name="wheelMass" value="2"/>


<xacro:include filename="$(find smartcar_description)/urdf/mycar.gazebo" />
<xacro:include filename="$(find smartcar_description)/urdf/materials.xacro" />
<xacro:include filename="$(find smartcar_description)/urdf/macros.xacro" />

<link name="base_link" />

<joint name="base_joint" type="fixed">
  <parent link="base_link"/>
  <child link="chassis"/>
  <origin xyz="0 0 0" rpy="0 0 0" />
  <axis xyz="0 0 0" />
</joint>

<link name='chassis'>
  <collision> 
    <origin xyz="0 0 ${wheelRadius*2}" rpy="0 0 0"/> 
    <geometry> 
      <cylinder length="${chassisHeight}" radius="${chassisRadius}"/>
    </geometry> 
  </collision>
  <visual> 
    <origin xyz="0 0 ${wheelRadius*2}" rpy="0 0 0"/> 
    <geometry> 
      <cylinder length="${chassisHeight}" radius="${chassisRadius}"/>
    </geometry> 
    <material name="orange"/>
  </visual>
  <inertial> 
    <origin xyz="0 0 ${wheelRadius*2}" rpy="0 0 0"/> 
    <mass value="${chassisMass}"/> 
    <cylinder_inertia m="${chassisMass}" r="${chassisRadius}" h="${chassisHeight}"/>
  </inertial>
</link>

<joint name="fixed_1" type="fixed">
  <parent link="chassis"/>
  <child link="caster_wheel_front"/>
  <origin xyz="0.15 0 0.05" rpy="0 0 0" />
  <axis xyz="0 0 0" />
</joint>

<link name="caster_wheel_front">
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${casterRadius}"/>
    </geometry>
  </collision>
  
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${casterRadius}"/>
    </geometry>
    <material name="red"/>
  </visual>

  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="${casterMass}"/>
    <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
  </inertial>
</link>

<joint name="fixed_2" type="fixed">
  <parent link="chassis"/>
  <child link="caster_wheel_back"/>
  <origin xyz="-0.15 0 0.05" rpy="0 0 0" />
  <axis xyz="0 0 0" />
</joint>

<link name="caster_wheel_back">
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${casterRadius}"/>
    </geometry>
  </collision>
  
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${casterRadius}"/>
    </geometry>
    <material name="red"/>
  </visual>

  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="${casterMass}"/>
    <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
  </inertial>
</link>

<joint name="left_wheel_hinge" type="continuous">
  <parent link="chassis"/>
  <child link="left_wheel"/>
<origin xyz="0 0.15 ${wheelRadius}" rpy="0 0 0" />
  <axis xyz="0 1 0" rpy="0 0 0" />
  <limit effort="100" velocity="100"/>
  <joint_properties damping="0.0" friction="0.0"/>
</joint>

<link name="left_wheel">
  <collision>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
    <material name="blue"/>
  </visual>

  <inertial>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <mass value="${wheelMass}"/>
    <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
  </inertial>
</link>

<transmission name="left_trans">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="left_wheel_hinge"> 
  	<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="leftMotor">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<joint name="right_wheel_hinge" type="continuous">
  <parent link="chassis"/>
  <child link="right_wheel"/>
<origin xyz="0 -0.15 ${wheelRadius}" rpy="0 0 0" />
  <axis xyz="0 1 0" rpy="0 0 0" />
  <limit effort="100" velocity="100"/>
  <joint_properties damping="0.0" friction="0.0"/>
</joint>

<link name="right_wheel">
  <collision>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
    <material name="blue"/>
  </visual>

  <inertial>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <mass value="${wheelMass}"/>
    <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
  </inertial>
</link>

<transmission name="right_trans">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="right_wheel_hinge">
  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
   </joint>
  <actuator name="rightMotor">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
  <origin xyz="0.175 0 ${chassisHeight+casterRadius*2+0.025}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera"/>
  </joint>

  <link name="camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${cameraSize/2} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${cameraSize/2} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${cameraMass}" />
      <box_inertia m="${cameraMass}" x="${cameraSize/2}" y="${cameraSize}" z="${cameraSize}" />
    </inertial>
  </link>

  <joint name="camera_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
    <parent link="camera"/>
    <child link="camera_link_optical"/>
  </joint>

  <link name="camera_link_optical">
  </link>

  <joint name="to_laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${chassisHeight+casterRadius*2+0.05}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="laser_link"/>
  </joint>

  <link name='laser_link'>
    <collision> 
      <origin xyz="0 0 0" rpy="0 0 0"/> 
      <geometry> 
        <cylinder length="0.1" radius="0.025"/>
      </geometry> 
    </collision>
    <visual> 
      <origin xyz="0 0 0" rpy="0 0 0"/> 
      <geometry> 
        <cylinder length="0.1" radius="0.025"/>
      </geometry> 
    </visual>
    <inertial> 
      <origin xyz="0 0 0" rpy="0 0 0"/> 
      <mass value="${cameraMass}"/> 
      <cylinder_inertia m="${cameraMass}" r="0.025" h="0.1"/>
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 0 0" />
    <origin xyz="-0.025 -0.025 0.05" rpy="0 0 0"/>
    <parent link="laser_link"/>
    <child link="laser_hokuyo"/>
  </joint>

  <link name="laser_hokuyo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://smartcar_description/meshes/hokuyo.dae"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black"/>
      <geometry>
        <mesh filename="package://smartcar_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1e-5" />
      <box_inertia m="1e-5" x="0.05" y="0.05" z="0.05" />
    </inertial>
  </link>




</robot>
